name: deploy

on: 
  workflow_call:
    inputs:
      MODE:
        required: true
        type: string
      PORT:
        required: true
        type: number
      REMOTE_HOST:
        required: true
        type: string
      NAME:
        required: true
        type: string
      INSTANCES:
        required: false
        type: number
        default: 1
      OSS:
        required: false
        type: string
    secrets:
      SSH_DEPLOY_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install frontend dependencies
      run: npm ci
      
    - name: Build frontend
      run: npm run build
      
    - name: Install server dependencies
      run: |
        cd server
        npm ci
        
    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r server/* deploy/
        cp pm2.config.js deploy/
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ inputs.REMOTE_HOST }}
        username: root
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        port: 22
        script: |
          # 停止现有服务
          pm2 stop ${{ inputs.NAME }} || true
          pm2 delete ${{ inputs.NAME }} || true
          
          # 创建应用目录
          mkdir -p /var/www/${{ inputs.NAME }}
          
          # 备份当前版本
          if [ -d "/var/www/${{ inputs.NAME }}/current" ]; then
            mv /var/www/${{ inputs.NAME }}/current /var/www/${{ inputs.NAME }}/backup-$(date +%Y%m%d-%H%M%S)
          fi
          
          # 创建新版本目录
          mkdir -p /var/www/${{ inputs.NAME }}/current
          
    - name: Upload files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ inputs.REMOTE_HOST }}
        username: root
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        port: 22
        source: "deploy/*"
        target: "/var/www/${{ inputs.NAME }}/current/"
        strip_components: 1
        
    - name: Start application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ inputs.REMOTE_HOST }}
        username: root
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        port: 22
        script: |
          cd /var/www/${{ inputs.NAME }}/current
          
          # 设置环境变量
          export NODE_ENV=${{ inputs.MODE }}
          export PORT=${{ inputs.PORT }}
          export NAME=${{ inputs.NAME }}
          
          # 启动应用
          pm2 start pm2.config.js
          pm2 save
          
          # 检查应用状态
          sleep 5
          pm2 status ${{ inputs.NAME }}