name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      MODE: 'production'
      PORT: 3000
      REMOTE_HOST: 8.159.133.190
      NAME: 'netease-music-prod'
      INSTANCES: 2
    secrets:
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}