name: Deploy to Development

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml@main
    with:
      MODE: 'development'
      PORT: 3001
      REMOTE_HOST: 8.159.133.190
      NAME: 'netease-music-dev'
      INSTANCES: 1
    secrets:
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}