name: Deploy to Development

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'development'
        type: choice
        options:
        - development
        - testing

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      MODE: 'development'
      PORT: 3001
      REMOTE_HOST: 8.159.133.190
      NAME: 'netease-music-dev'
      INSTANCES: 1
    secrets: inherit